# Generated by Django 4.1.7 on 2023-04-21 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название книги')),
                ('description', models.TextField(verbose_name='Описание книги')),
                ('image', models.ImageField(upload_to='', verbose_name='Обложка книги')),
                ('linkLitress', models.TextField(blank=True, null=True, verbose_name='Ссылка на покупку')),
                ('linkDowload', models.TextField(blank=True, null=True, verbose_name='Ссылка на загрузку фрагмента')),
                ('linkOnline', models.TextField(blank=True, null=True, verbose_name='Ссылка на онлайн фрагмент')),
                ('ageRestriction', models.IntegerField(verbose_name='Возрастное ограничение')),
                ('date_of_writing', models.DateField(verbose_name='Дата написания')),
                ('value', models.IntegerField(verbose_name='Количество страниц')),
                ('isbn', models.CharField(max_length=200, verbose_name='Международный номер книги')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_main.author', verbose_name='Автор книги')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('source', models.CharField(max_length=100, verbose_name='Источник Новости')),
                ('pudlicachia_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'новости',
            },
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotes', models.TextField(verbose_name='Цитата')),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_main.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название жанра')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_main.genre', verbose_name='Жанр книги'),
        ),
    ]
