# Generated by Django 4.1.7 on 2023-05-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('enail', models.EmailField(max_length=254)),
                ('namber', models.IntegerField(verbose_name='Номер телефона')),
                ('adress', models.TextField(verbose_name='Адрес')),
            ],
        ),
    ]
